
###
GRPC localhost:5050/pb.AgentQueue/Insert

{
  "isFound": true,
  "name": "string",
  "agentState": 0,
  "cif": "string",
  "id": "2"
}

###
GRPC localhost:5050/pb.AgentQueue/Poll

###
GRPC localhost:5050/pb.AgentQueue/List
